# The URL the site will be built for
base_url = "https://blog.generative.codes"

# The site title and description; used in feeds by default.
title = "generative.codes"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "slim"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


taxonomies = [
    {name = "tags", paginate_by = 5, rss = true}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Show a summary of a post in a list
slim_summary = true
# Show the content of a post in a list
slim_content = true
# Links to show at the top of the menu
slim_menu = [
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/digital_garden", name = "Digital Garden"}
]
# Links to show at the bottom of the menu
slim_social = [
    {url = "https://github.com/generativecodes", name = "Github"},
    {url = "https://instagram.com/generative.codes", name = "Instagram"}]
